import { AsideComponent } from "./Aside.styles";
import { NewsWrapper } from "../../styledComponents/Wrappers/Wrappers.styles";

export const Aside = () => {
  return (
    <AsideComponent>
      <div
        style={{
          width: "calc(100% - 10px)",
        }}
      >
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
        <NewsWrapper>Hello</NewsWrapper>
      </div>
    </AsideComponent>
  );
};
